FROM wordpress:6.5.5-php8.2-apache

# Set permissions for WordPress files
#RUN chown -R www-data:www-data /var/www/html

# Add the FS_METHOD definition directly to wp-config.php
#RUN echo "define('FS_METHOD', 'direct');" >> /var/www/html/wp-config.php